# Generated by Django 5.2.6 on 2026-01-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_add_user_profile_coins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=64)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('kind_moments', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('hurt_moments', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simulator.practicesession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
